"""add user_id col in Post

Revision ID: 2964f6a99644
Revises: 118e38e7baea
Create Date: 2026-06-08 15:47:47.703233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2964f6a99644'
down_revision: Union[str, Sequence[str], None] = '118e38e7baea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###
