"""fix camelcase to snakecase

Revision ID: 4bd69833e68e
Revises: 5e61b176fd53
Create Date: 2026-06-10 11:16:50.109206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bd69833e68e'
down_revision: Union[str, Sequence[str], None] = '5e61b176fd53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('posts', 'deletedAt')
    op.drop_column('posts', 'updatedAt')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'deletedAt')
    op.drop_column('users', 'updatedAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('deletedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.add_column('posts', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('deletedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('posts', 'deleted_at')
    op.drop_column('posts', 'updated_at')
    # ### end Alembic commands ###
