"""add datetiem in posts model

Revision ID: 5e61b176fd53
Revises: 9430bf104f89
Create Date: 2026-06-10 10:31:30.499588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e61b176fd53'
down_revision: Union[str, Sequence[str], None] = '9430bf104f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('posts', sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('posts', sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'deletedAt')
    op.drop_column('posts', 'updatedAt')
    op.drop_column('posts', 'created_at')
    # ### end Alembic commands ###
